### ISSUE TITLE
Only seems to work as intended when already on same page as hash/id

### ISSUE THREAD

**Issue by michaeljblum** [brohlson/gatsby-plugin-anchor-links#1]
Thanks for your work on this, and it's a great idea (if I'm understanding the intention of the project correctly). Unfortunately, I'm only getting the scroll behavior upon clicking the anchorlink when I'm already on the same page as the destination hash/id.

This plugin is intended to work across different pages as well, right? I've been using [this plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-smoothscroll/) for same-page smooth-scrolling just fine, but have been struggling with getting similar behavior across pages. 

When I have more time I'll look into whether gatsby-plugin-layout, which I also have enabled for transition purposes, is messing with any of this (because I also tried something by hand to achieve the effect I'm looking for, which also didn't work as expected).

**Comment by brohlson** [comment]
The problem here is that browsers will automatically land you on the hash.  If you have no offset for something like a header, you won't notice anything being done.  

I thought about restructuring the cross-page action to strip out the hash, then scroll to the intended target from memory - but it kinda seems like an anti-pattern.  Maybe I'll play around with adding some sort of boolean prop to enforce this on an optional basis.

**Comment by brohlson** [comment]
Gonna work this into v1.1.0

https://github.com/brohlson/gatsby-plugin-anchor-links/projects/1#card-32631512

**Comment by ryansrofe** [comment]
By adding the offset to the config it works on other pages in the site. At least this is what worked for me.

**Comment by brohlson** [comment]
Full page scrolling onRouteChange added in https://github.com/brohlson/gatsby-plugin-anchor-links/pull/3 with `stripHash` prop

**Comment by michaeljblum** [comment]
Awesome - have been busy with other work the last few days but will definitely try this out over the weekend.

**Comment by michaeljblum** [comment]
Super late but I just found out what was preventing me from seeing any effect - the projects I tried this plugin out in both had code like
 ```
 export const wrapPageElement = ({ element, props }) => {
  return <Layout {...props}>{element}</Layout>;
};
``` 
inside of gatsby-ssr.js and gatsby-browser.js, in order to prevent the layout from unmounting upon route changes (in order to allow for page transitions to work, particularly the exit animations). 

Tried this plugin out in a Gatsby project without code in ssr and browser to prevent unmounting of layout and AnchorLink worked exactly as expected 🍻

Gonna try and see if I can get this plugin (or the functionality its aiming for - will use your blogpost on the topic as reference) work alongside the logic I have allowing me to use page transitions.
