### ISSUE TITLE
Adding slashes to links results in delay on clicking

### ISSUE THREAD

**Issue by piersolenski** [brohlson/gatsby-plugin-anchor-links#10]
Hey! I changed the formatting of my hashed paths from `#watch` to `/#watch` to avoid the error `External link #watch was detected in a Link component. Use the Link component only for internal links. See: https://gatsby.dev/internal-links.`, however now I get a small yet frustrating delay when the links are clicked - any idea why this could be happening? Thanks!

**Comment by brohlson** [comment]
The `path` + `hash` format is what should be used to ensure every case works as intended.  I haven't experienced the delay you're experiencing - if you can share a prod link or repo I can take a peek next time do some work on the plugin.
