### ISSUE TITLE
AnchorLink can not be used with Material Ui

### ISSUE THREAD

**Issue by ohlr** [brohlson/gatsby-plugin-anchor-links#12]
```
import { Link } from "@material-ui/core";
import { AnchorLink } from "gatsby-plugin-anchor-links";

<Link
  component={AnchorLink}
  to="/about"
  variant="h6"
  color="primary"
  gutterBottom
  stripHash  >
 about
</Link>
```
This code produces the following browser errors:
> Warning: Failed prop type: Invalid prop `component` supplied to `ForwardRef(Link)`. Expected an element type that can hold a ref. Did you accidentally **provide a plain function component instead**? For more information see https://material-ui.com/r/caveat-with-refs-guide
> 
> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

--

I use Material Ui. Passing GatsbyLink to Material UI Links works fine. But AnchorLinks can not be passed to the component prop. The [MUi Docs](https://material-ui.com/api/link/ ) say that AnchorLinks must be able to hold a Ref for this to work.

**Comment by brohlson** [comment]
I'd be happy to take a look at a pull request if you want to take a stab at it - this seems like quite an edge case

**Comment by brohlson** [comment]
What happens when you wrap it in a class component?

```
class AnchorLinkClassComponent extends Component {
 constructor(props) {
  super(props)
}
 return <AnchorLink {...this.props}/>
}
```
Seems like quite an edge case.

**Comment by ohlr** [comment]
```
import * as React from "react";
import { AnchorLink, AnchorLinkProps } from "gatsby-plugin-anchor-links";

class AnchorLinkClass extends React.Component<AnchorLinkProps> {
  constructor(props: AnchorLinkProps) {
    super(props);
  }
  render() {
    return <AnchorLink {...this.props} />;
  }
}

export default AnchorLinkClass;
```
solved it. Thanks

**Comment by MartinDawson** [comment]
You don't need a class for this.

```
  component={forwardRef((props, ref) => (
                  <AnchorLink {...props} gatsbyLinkProps={{ ref }} />
                ))}
```

Although I don't know why their is a prop called `gatsbyLinkProps`, when you could just do this in the AnchorLink itself, {...props} which would stop issues like these.
