### ISSUE TITLE
Warning when using links without selector

### ISSUE THREAD

**Issue by ohlr** [brohlson/gatsby-plugin-anchor-links#13]
`Anchor path should contain an absolute root path `/` and selector `#` Ex: /about#team`

https://www.gatsbyjs.org/packages/gatsby-plugin-anchor-links/#component-usage
Here the example shows an link without selector.
However using the plugin this way, throws the above warning.

I believe it should be fine to use paths without selector thus I would recommend not issuing a warning.

**Comment by brohlson** [comment]
I'm gonna make these dev-only warnings in the next minor version

**Comment by ohlr** [comment]
but is it really an issue not to use a selector?
the root / I can underestand but having no # should be totally fine I suppose.
