### ISSUE TITLE
Use anchor plugins on markdown generated pages?

### ISSUE THREAD

**Issue by banglabs-eu** [brohlson/gatsby-plugin-anchor-links#15]
I have a massive [Markdown post](http://devseamlessio.com.s3-website.eu-central-1.amazonaws.com/articles/jxa-snippets-collection) and would like to apply the same smooth scroll anchor links gives as on Gatsby made pages. How would I apply to all Gatsby generated links?

**Comment by brohlson** [comment]
Should work with MDX 🤷 
https://www.gatsbyjs.org/docs/mdx/
