### ISSUE TITLE
Scroll to location when using direct URL

### ISSUE THREAD

**Issue by mbwatson** [brohlson/gatsby-plugin-anchor-links#18]
Thanks for this plugin! Scrolling to destinations within a page work great. Users can land on some page, `example.com/page`, and then clicking an anchor link, say `#some-location`, scrolls the user to that location, as expected.

However, a request has come my way for implementing that same functionality when someone visits the URL `example.com/page#some-location` directly. That is, scroll to the desired location once the page has rendered.

Is this already possible, or is that functionality you've considered implementing for this plugin? Not sure how it would work in this case--perhaps a delay, but I'm not sure.

**Comment by ansh** [comment]
You can simply use the normal `<Link>` in gatsby to do this. [This article](https://medium.com/@chrisfitkin/how-to-smooth-scroll-links-in-gatsby-3dc445299558) helps.

**Comment by brohlson** [comment]
Closing - AnchorLink component shouldn't be concerned with this
