### ISSUE TITLE
Clarify errorTypes.IMPROPPER_FORMATTING message

### ISSUE THREAD

**Issue by Undistraction** [brohlson/gatsby-plugin-anchor-links#24]
Given that anchor tags without paths are perfectly valid, it would be helpful to explain why they 'should contain an absolute root path'. It isn't mentioned anywhere in the README.

**Comment by brohlson** [comment]
They are not valid - it is mentioned in the readme. 

`You can provide anchor or non-anchor links to this component for ease of use. If you use it as an anchor component, be sure to include both a base path and hash in the to string.`
