### ISSUE TITLE
delay while page content loads?

### ISSUE THREAD

**Issue by mikeriley131** [brohlson/gatsby-plugin-anchor-links#26]
Thanks for building this.

I'm using the plugin on a site that is very image heavy.
I am linking from the homepage to anchors on interior pages.
On the first try, it seems to be hitting the anchor correctly but the anchor then moves as my images load.
On subsequent tries, it lands correctly and stays in place.
Is there anyway to be sure that content has loaded before landing on the anchor?

**Comment by brohlson** [comment]
It's very possible if you are using inline images that the length of the page is changing as the images are loading - throwing off the scrolling action.  I'd recommend using `gatsby-image` or some solution which respects the image dimensions before loading.
