### ISSUE TITLE
Please mention it scrolls to element IDs in documentation

### ISSUE THREAD

**Issue by bullett445** [brohlson/gatsby-plugin-anchor-links#29]
Hi,
took two hours of my life that this plugin doesn't scroll to a `<a href='#anchor'></a>` but to a e.g. `<span id='anchor'></span>`

It would be nice if you could mention that in the documentation.

Jan

**Comment by nminchow** [comment]
(I'm not sure what the policy is on closed issues)

This may be standard behavior for anchor navigation, but I think something to this effect may be nice to mention in the docs. I assumed IDs were the target, but was having an unrelated issue and was starting to question if I had made a bad assumption.
