### ISSUE TITLE
Change URL when clicking on an AnchorLink

### ISSUE THREAD

**Issue by dsebastien** [brohlson/gatsby-plugin-anchor-links#31]
Hello,

First of all, thanks for creating/sharing this plugin!

It works perfectly for my needs, but there's one issue I have with it. When I am on Page `/X` and click on an `AnchorLink` pointing to `/X#some-anchor`, then it does scroll to the anchor, but the URL doesn't change.

Would it be possible to add this behavior as an option, or to pass the target of the `AnchorLink` to the `onAnchorLinkClick` function?

I'm using this here: https://www.dev-concepts.dev/table-of-contents, for the overview on the right; clicking on one of the boxes brings the reader to one of the anchors.

**Comment by brohlson** [comment]
@dsebastien  You could do this in a function passed to `AnchorLink`

```javascript
<AnchorLink to={`/#howdy`} onAnchorLinkClick={() => myUrlChangeFunc("#howdy")} />
```

🤠

**Comment by dsebastien** [comment]
Works great, thanks.

For those interested, I've defined my links as follows:

```
<AnchorLink
                  to="/table-of-contents/#software-craft"
                  onAnchorLinkClick={() =>
                    history.pushState(null, "Software Development Concepts - Table of contents (draft) - Software craft", "#software-craft")
                  }
                  aria-label="Part 1: Software craft"
                >...
```
