### ISSUE TITLE
Giving "active" class to a link when location matches link path?

### ISSUE THREAD

**Issue by too-soon** [brohlson/gatsby-plugin-anchor-links#35]
Has anyone tried this? A google search gives nothing.

**Comment by Hahlh** [comment]
I haven't, but if I would, I would first look at the props that I can pass through to Gatsby Link, especially [GatsbyLinkProps](https://github.com/brohlson/gatsby-plugin-anchor-links#anchorlink-props).

**Comment by brohlson** [comment]
Unless `GatsbyLink` supports this - you'd have to write your own `className` logic for this.
