### ISSUE TITLE
No smooth scroll for anchor, only for offset

### ISSUE THREAD

**Issue by Sir-Will** [brohlson/gatsby-plugin-anchor-links#39]
I'm not getting a smooth scroll to the anchor, it jumps to the anchor and does a smooth scroll to the offset.
Before I was using `react-anchor-link-smooth-scroll` where the smooth scroll is working.

Am I missing something?

```javascript
import { AnchorLink } from 'gatsby-plugin-anchor-links'
import React from 'react'
import PropTypes from 'prop-types'
import { IntlContextConsumer } from 'gatsby-plugin-intl'

const AnchorLinkIntl = ({ to, language, children, ...rest }) => (
<IntlContextConsumer>
	{intl => {
		const languageLink = language || intl.language
		const link = intl.routed || language ? `/${languageLink}${to}` : `${to}`

		return (
			<AnchorLink {...rest} to={link}>
				{children}
			</AnchorLink>
		)
	}}
</IntlContextConsumer>
)

AnchorLinkIntl.propTypes = {
	children: PropTypes.node.isRequired,
	to: PropTypes.string,
	language: PropTypes.string
}

AnchorLinkIntl.defaultProps = {
	to: ''
}

export default AnchorLinkIntl
```

**Comment by brohlson** [comment]
It's hard to tell what your actual `to` values end up being, but assuming they have both a path and a hash IE `/path#hash` and you've configured the plugin in `gatsby-config` - should be working.

**Comment by Sir-Will** [comment]
The `to` is `/de/#hash`, while the open site is `/de` but I also tried without the language prefix like `/#hash` and it didn't smooth scroll.

**Comment by Sir-Will** [comment]
I see that you are using gatsby version to for your site, I'm using 3.2, could this be the reason?
Do you know any site which is using 3.2 and this plugin?

**Comment by Sir-Will** [comment]
Found the issue, it was returning a different component because it found the newly added `/` and counted it as internal link instead of a hash link.
