### ISSUE TITLE
using stripHash doesnt work on production

### ISSUE THREAD

**Issue by mustofa-binary** [brohlson/gatsby-plugin-anchor-links#9]
i tried to use the plugin like this in gatsby-config.js
```
        {
            resolve: 'gatsby-plugin-anchor-links',
            options: {
                offset: -100,
            },
        },
```
and 
```
 <AnchorLink to="/#how-it-works" stripHash>How it works</AnchorLink>
 <AnchorLink to="/#about-us" stripHash>About us</AnchorLink>
 <AnchorLink to="/#our-clients" stripHash>Testimonials</AnchorLink>
```

when run in local it works, smooth scroll also works, but when i deploy to netlify, eveytime i click on the link, it just goes to the top page, if i dont use stripHash, it will just go to the target, no smooth scroll.

**Comment by brohlson** [comment]
Can you share a production link & repo?

**Comment by mohammed786** [comment]
I am facing a similar issue you can check it out here - https://www.loginradius.com/docs/developer/api
